### ISSUE TITLE
Terminal Issue!

### ISSUE THREAD

**Issue by Deep-py** [Snaacky/Sapphire#5]
First of all hello, I'm a great fan of your projects they have really helped me improve on reverse engineering topic.
The Issue I had is **_When I run the file it just appears for a second and disappears immediately_**. I tried a lot of things to solve this - like making a loop inside a While True loop - but I guess my knowledge or thinking style is not enough(I believe this is a disadvantage of my age- I'm 14) for this problem. So I'm asking you. Are you know the solution or something that helps me solve this solution? If you help appreciated it.

btw English isn't my first language so if you spot a Writing fail don't mind it :P 

- <3 Derin Onder aka D0PE

**Comment by Snaacky** [comment]
How are you executing the script? It sounds like you're trying to execute the script by clicking the file. You need to pop open a cmd/powershell instance and run `python sapphire.py` or whatever you named the script as.

**Comment by Deep-py** [comment]
it says this 

http://prntscr.com/ubedef

but doing nothing.

**Comment by Snaacky** [comment]
Is your cmd being run as admin? 

The top of your cmd.exe window should say "Administrator C:\Windows\System32\cmd.exe" when ran as admin rather than "C:\Windows\System32\cmd.exe" when running as a non-privileged user.

**Comment by Deep-py** [comment]
I just Run the terminal as admin but it didn't work either. it debugs with the pymem but doing nothing.

**Comment by Snaacky** [comment]
Have you updated the memory addressees and offsets to reflect the latest usage? I don't keep those updated in the repo and CS:GO gets updates somewhat frequently now.

**Comment by Deep-py** [comment]
oh ok i will try.

**Comment by Snaacky** [comment]
Did you resolve your issue?
