### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by markojerry** [Snaacky/Sapphire#7]
Hi, I tried running your script in cmd with admin privileges but it errored with the following output:

```
File "sapphire.py", line 5, in <module>
    from win32gui import GetWindowText, GetForegroundWindow
ImportError: DLL load failed: The specified module was not found.
```

Any ideas?

**Comment by Snaacky** [comment]
Looks like you're missing the pywin32api. Closing as this is user error and not an issue with the repository.
